package com.codelens.controller;

import com.codelens.dto.GenerateReportRequestRecord;
import com.codelens.dto.ReportDetailsResponseRecord;
import com.codelens.dto.ReportResponseRecord;
import com.codelens.service.IReportService;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST Controller managing user reports and export operations.
 */
@RestController
@RequestMapping("/api/v1/reports")
public class ReportController {

    private static final Logger log = LoggerFactory.getLogger(ReportController.class);

    private final IReportService reportService;

    public ReportController(IReportService reportService) {
        this.reportService = reportService;
    }

    /**
     * Triggers generation of a new static report.
     *
     * @param userDetails Authenticated user details
     * @param request Report generation request payload
     * @return ResponseEntity with generated ReportResponseRecord
     */
    @PostMapping
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ReportResponseRecord> generateReport(
            @AuthenticationPrincipal UserDetails userDetails,
            @Valid @RequestBody GenerateReportRequestRecord request) {
        log.info("REST Request to generate report for user: {}", userDetails.getUsername());
        ReportResponseRecord response = reportService.generateReport(userDetails.getUsername(), request);
        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    /**
     * Lists reports generated by the authenticated user.
     *
     * @param userDetails Authenticated user details
     * @return ResponseEntity containing list of ReportResponseRecord
     */
    @GetMapping
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<List<ReportResponseRecord>> getCurrentUserReports(
            @AuthenticationPrincipal UserDetails userDetails) {
        log.info("REST Request to list reports for user: {}", userDetails.getUsername());
        List<ReportResponseRecord> reports = reportService.getUserReports(userDetails.getUsername());
        return ResponseEntity.ok(reports);
    }

    /**
     * Retrieves full content and metadata of a specific report.
     *
     * @param reportId Report ID
     * @param userDetails Authenticated user details
     * @return ResponseEntity containing ReportDetailsResponseRecord
     */
    @GetMapping("/{reportId}")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<ReportDetailsResponseRecord> getReportById(
            @PathVariable Long reportId,
            @AuthenticationPrincipal UserDetails userDetails) {
        log.info("REST Request to get report ID {} for user: {}", reportId, userDetails.getUsername());
        ReportDetailsResponseRecord response = reportService.getReportById(reportId, userDetails.getUsername());
        return ResponseEntity.ok(response);
    }
}
