<script setup lang="ts">
import { ref } from 'vue';

interface ReportTemplate {
  id: string;
  title: string;
  description: string;
  category: 'COMPLIANCE' | 'PERFORMANCE' | 'SECURITY' | 'BILLING';
  icon: string;
}

interface ExportHistoryItem {
  id: string;
  reportTitle: string;
  format: 'PDF' | 'CSV' | 'JSON' | 'MARKDOWN';
  generatedAt: string;
  fileSize: string;
  status: 'COMPLETED' | 'PROCESSING' | 'FAILED';
  generatedBy: string;
}

const templates: ReportTemplate[] = [
  {
    id: 'rpt_compliance',
    title: 'SOC2 & Executive Governance Report',
    description: 'Comprehensive audit summary of admin roles, permission changes, and platform security policies.',
    category: 'COMPLIANCE',
    icon: '🛡️',
  },
  {
    id: 'rpt_performance',
    title: 'AI Code Review & Latency Benchmarks',
    description: 'Telemetry metrics on AI provider model speeds, token consumption, and code review turnarounds.',
    category: 'PERFORMANCE',
    icon: '⚡',
  },
  {
    id: 'rpt_security',
    title: 'User Access & Session Revocation Log',
    description: 'Detailed security activity log of active user sessions, failed logins, and revoked access tokens.',
    category: 'SECURITY',
    icon: '🔑',
  },
  {
    id: 'rpt_billing',
    title: 'Infrastructure & Token Usage Telemetry',
    description: 'Breakdown of AI token costs, database query loads, and storage consumption across repositories.',
    category: 'BILLING',
    icon: '📊',
  },
];

const selectedTemplateId = ref<string>('rpt_compliance');
const dateRange = ref<string>('30d');
const exportFormat = ref<'PDF' | 'CSV' | 'JSON' | 'MARKDOWN'>('PDF');
const isGenerating = ref<boolean>(false);
const generationProgress = ref<number>(0);

const exportHistory = ref<ExportHistoryItem[]>([
  {
    id: 'exp_101',
    reportTitle: 'SOC2 & Executive Governance Report',
    format: 'PDF',
    generatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    fileSize: '2.4 MB',
    status: 'COMPLETED',
    generatedBy: 'admin@codelens.ai',
  },
  {
    id: 'exp_102',
    reportTitle: 'AI Code Review & Latency Benchmarks',
    format: 'CSV',
    generatedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    fileSize: '840 KB',
    status: 'COMPLETED',
    generatedBy: 'admin@codelens.ai',
  },
  {
    id: 'exp_103',
    reportTitle: 'User Access & Session Revocation Log',
    format: 'JSON',
    generatedAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    fileSize: '1.1 MB',
    status: 'COMPLETED',
    generatedBy: 'security@codelens.ai',
  },
]);

const handleGenerateReport = async () => {
  if (isGenerating.value) return;
  isGenerating.value = true;
  generationProgress.value = 10;

  const interval = setInterval(() => {
    if (generationProgress.value < 90) {
      generationProgress.value += 20;
    }
  }, 250);

  setTimeout(() => {
    clearInterval(interval);
    generationProgress.value = 100;

    const template = templates.find((t) => t.id === selectedTemplateId.value);
    const newExport: ExportHistoryItem = {
      id: `exp_${Date.now()}`,
      reportTitle: template?.title || 'System Export',
      format: exportFormat.value,
      generatedAt: new Date().toISOString(),
      fileSize: exportFormat.value === 'PDF' ? '3.1 MB' : '650 KB',
      status: 'COMPLETED',
      generatedBy: 'admin@codelens.ai',
    };

    exportHistory.value.unshift(newExport);
    isGenerating.value = false;
  }, 1500);
};

const handleDownloadReport = (item: ExportHistoryItem) => {
  const content = `CodeLens Report: ${item.reportTitle}\nFormat: ${item.format}\nGenerated At: ${item.generatedAt}\nGenerated By: ${item.generatedBy}\n`;
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${item.reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_')}.${item.format.toLowerCase()}`;
  link.click();
};
</script>

<template>
  <div class="reports-view">
    <div class="page-header">
      <div>
        <h1 class="page-title">Executive Reports & Data Export</h1>
        <p class="page-description">Generate, schedule, and export platform compliance, security telemetry, and AI metrics.</p>
      </div>
    </div>

    <!-- Generator Panel -->
    <div class="generator-card">
      <h2 class="card-title">1. Select Report Template</h2>
      
      <div class="templates-grid">
        <div
          v-for="tpl in templates"
          :key="tpl.id"
          class="template-card"
          :class="{ selected: selectedTemplateId === tpl.id }"
          @click="selectedTemplateId = tpl.id"
        >
          <div class="card-top">
            <span class="tpl-icon">{{ tpl.icon }}</span>
            <span class="category-badge" :class="tpl.category.toLowerCase()">{{ tpl.category }}</span>
          </div>
          <h3 class="tpl-title">{{ tpl.title }}</h3>
          <p class="tpl-desc">{{ tpl.description }}</p>
        </div>
      </div>

      <div class="config-divider"></div>

      <h2 class="card-title">2. Export Configuration</h2>
      <div class="config-row">
        <div class="field-group">
          <label class="field-label">Date Range</label>
          <select v-model="dateRange" class="form-select">
            <option value="7d">Last 7 Days</option>
            <option value="30d">Last 30 Days</option>
            <option value="90d">Last 90 Days</option>
            <option value="1y">Year to Date (YTD)</option>
          </select>
        </div>

        <div class="field-group">
          <label class="field-label">Output Format</label>
          <div class="format-buttons">
            <button
              v-for="fmt in (['PDF', 'CSV', 'JSON', 'MARKDOWN'] as const)"
              :key="fmt"
              type="button"
              class="fmt-btn"
              :class="{ active: exportFormat === fmt }"
              @click="exportFormat = fmt"
            >
              {{ fmt }}
            </button>
          </div>
        </div>

        <div class="action-container">
          <button class="generate-btn" :disabled="isGenerating" @click="handleGenerateReport">
            <span v-if="isGenerating">Compiling {{ generationProgress }}%...</span>
            <span v-else>Generate {{ exportFormat }} Report</span>
          </button>
        </div>
      </div>
    </div>

    <!-- Recent Exports Table -->
    <div class="history-card">
      <h2 class="card-title">Recent Generated Exports</h2>
      <div class="table-responsive">
        <table class="history-table">
          <thead>
            <tr>
              <th>Report Title</th>
              <th>Format</th>
              <th>Generated At</th>
              <th>File Size</th>
              <th>Author</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in exportHistory" :key="item.id">
              <td class="title-cell">{{ item.reportTitle }}</td>
              <td>
                <span class="format-badge" :class="item.format.toLowerCase()">{{ item.format }}</span>
              </td>
              <td class="date-cell">{{ new Date(item.generatedAt).toLocaleString() }}</td>
              <td class="size-cell">{{ item.fileSize }}</td>
              <td class="author-cell">{{ item.generatedBy }}</td>
              <td>
                <span class="status-badge" :class="item.status.toLowerCase()">● {{ item.status }}</span>
              </td>
              <td>
                <button class="download-btn" @click="handleDownloadReport(item)">
                  Download
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.reports-view {
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.page-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--admin-text-primary);
  margin-bottom: 0.25rem;
}
.page-description {
  color: var(--admin-text-secondary);
  font-size: 0.9rem;
}

.generator-card, .history-card {
  background: var(--admin-bg-surface);
  border: 1px solid var(--admin-border-color);
  border-radius: var(--admin-radius-md);
  padding: 1.5rem;
  box-shadow: var(--admin-shadow-sm);
}

.card-title {
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--admin-text-primary);
  margin-bottom: 1rem;
}

.templates-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.template-card {
  border: 1px solid var(--admin-border-color);
  border-radius: var(--admin-radius-sm);
  padding: 1rem;
  background: var(--admin-bg-surface-hover);
  cursor: pointer;
  transition: all 0.15s ease;

  &:hover {
    border-color: var(--admin-primary);
    transform: translateY(-2px);
  }

  &.selected {
    border-color: var(--admin-primary);
    background: var(--admin-primary-glow);
  }
}

.card-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.75rem;
}

.tpl-icon { font-size: 1.25rem; }
.tpl-title { font-size: 0.95rem; font-weight: 700; color: var(--admin-text-primary); margin-bottom: 0.35rem; }
.tpl-desc { font-size: 0.8rem; color: var(--admin-text-muted); line-height: 1.4; }

.category-badge {
  font-size: 0.65rem;
  font-weight: 800;
  padding: 0.15rem 0.4rem;
  border-radius: 4px;

  &.compliance { color: #3b82f6; background: rgba(59, 130, 246, 0.15); }
  &.performance { color: #10b981; background: rgba(16, 185, 129, 0.15); }
  &.security { color: #ef4444; background: rgba(239, 68, 68, 0.15); }
  &.billing { color: #8b5cf6; background: rgba(139, 92, 246, 0.15); }
}

.config-divider {
  height: 1px;
  background: var(--admin-border-color);
  margin: 1.5rem 0;
}

.config-row {
  display: flex;
  align-items: flex-end;
  gap: 1.5rem;
  flex-wrap: wrap;
}

.field-group {
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}

.field-label {
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--admin-text-muted);
}

.form-select {
  padding: 0.5rem 0.8rem;
  border-radius: var(--admin-radius-sm);
  border: 1px solid var(--admin-border-color);
  background: var(--admin-bg-app);
  color: var(--admin-text-primary);
  font-size: 0.85rem;
}

.format-buttons {
  display: flex;
  gap: 0.4rem;
}

.fmt-btn {
  padding: 0.45rem 0.8rem;
  border-radius: var(--admin-radius-sm);
  border: 1px solid var(--admin-border-color);
  background: var(--admin-bg-app);
  color: var(--admin-text-muted);
  font-size: 0.78rem;
  font-weight: 700;
  cursor: pointer;
  transition: all 0.15s ease;

  &.active, &:hover {
    background: var(--admin-primary);
    color: #ffffff;
    border-color: var(--admin-primary);
  }
}

.action-container { margin-left: auto; }

.generate-btn {
  padding: 0.6rem 1.25rem;
  border-radius: var(--admin-radius-sm);
  border: none;
  background: var(--admin-primary);
  color: #ffffff;
  font-weight: 700;
  font-size: 0.88rem;
  cursor: pointer;

  &:hover:not(:disabled) {
    background: var(--admin-primary-hover);
  }
  &:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }
}

.table-responsive { overflow-x: auto; }

.history-table {
  width: 100%;
  border-collapse: collapse;
  text-align: left;
  font-size: 0.85rem;

  th, td { padding: 0.85rem 1rem; border-bottom: 1px solid var(--admin-border-color); }
  th { font-size: 0.75rem; text-transform: uppercase; color: var(--admin-text-muted); font-weight: 600; }
}

.title-cell { font-weight: 600; color: var(--admin-text-primary); }
.date-cell, .size-cell, .author-cell { color: var(--admin-text-muted); font-size: 0.8rem; }

.format-badge {
  font-size: 0.7rem;
  font-weight: 800;
  padding: 0.15rem 0.4rem;
  border-radius: 4px;
  background: var(--admin-bg-app);
  color: var(--admin-text-primary);
}

.status-badge.completed {
  color: var(--admin-success);
  font-weight: 700;
}

.download-btn {
  padding: 0.35rem 0.7rem;
  border-radius: 4px;
  border: 1px solid var(--admin-primary);
  background: transparent;
  color: var(--admin-primary);
  font-size: 0.78rem;
  font-weight: 600;
  cursor: pointer;

  &:hover {
    background: var(--admin-primary);
    color: #ffffff;
  }
}
</style>
